### ISSUE TITLE
Device not getting recognised on Thunderbolt port.

### ISSUE THREAD

**Issue by cold-inferno** [leighsmith/midisport-macos#23]
Issue: Device not getting recognised with just a USB-C dongle.

Solution: Use a USB 2.0 hub in between to get it be recognised.

**Comment by leighsmith** [comment]
Thanks, a number of people have reported problems with devices, especially the Oxygen 8, which proved to be a USB cable issue. My hypothesis is that some of the USB receivers and drivers in the MIDISPORT and Oxygen 8 devices have fairly slow response times, so that they are sensitive to low quality USB cables which can roll off the edges of a digital signal. So certainly try swapping cables as a first step to diagnose problems. Thanks for your report.
