### ISSUE TITLE
Radium61 support?

### ISSUE THREAD

**Issue by joxyzan** [leighsmith/midisport-macos#38]
Greetings! I installed the driver on my 2021 M1 MacBook Pro (Monterey 12.6) in hope of getting my old M-Audio MIDI keyboard Radium61 come to life – with no effect. Is there any chance it could work with this driver or any future update of it?

Radium61's info from the USB device tree in macOS System Report: 

**Vendor-Specific Device:**
  Product ID: 0x1014
  Vendor ID: 0x0763  (M-Audio)
  Version:	0.01
  Speed: Up to 12 Mb/s
  Location ID: 0x01120000 / 3
  Current Available (mA): 500
  Current Required (mA): 100
  Extra Operating Current (mA): 0

**Comment by leighsmith** [comment]
Try the latest [v1.3.1 Release](https://github.com/leighsmith/midisport-macos/releases/tag/v1.3.1) which addresses the problems with MacOS v12 not supporting Python v2 installations.

**Comment by joxyzan** [comment]
I had this in the back of my mind since January... and now I got the time and opportunity to try it... and it works! My Radium61 shows up as "Oxygen 8" in the Audio MIDI Setup – and it works fine in Garageband (including sliders and knobs). Thank you very much for giving life back to old hardware! 👻

PS: I guess you can list Radium49/61 as working and tested now?

**Comment by joxyzan** [comment]
I had this in the back of my mind since January... and now I got the time and opportunity to try it... and it works! My Radium61 shows up as "Oxygen 8" in the Audio MIDI Setup – and it works fine in Garageband (including sliders and knobs). Thank you very much for giving life back to old hardware! 👻

PS: I guess you can list Radium49/61 as working and tested now?

**Comment by leighsmith** [comment]
Ok great, thanks for the testing and advice. I've updated the README.

**Comment by bluroomstudio** [comment]
@leighsmith @Jay4Dolby - Reviving this old thread about the M-Audio Radium 61.

I have the exact same keyboard (Radium 61) and the same problem - only basic MIDI works, no transport controls.

My setup: 
- Mac Pro 5,1 running Sonoma via OpenCore Legacy Patcher
- Can test on both: Original USB 1.1 ports AND PCIe USB 3.0 card
- Same USB IDs as @Jay4Dolby: VID 0x0763, PID 0x2810

I read your 2022 analysis where you explained it needs a userspace driver (not compatible with midisport).

Simple question: 
Is there any update or progress since 2022? 
Would you be willing to guide me in creating a driver? 
I'm ready to do the testing and can provide any logs needed.

Even just pointing me in the right direction would be a huge help.

Thanks!
