### ISSUE TITLE
Oxygen 8 not working on Big Sur

### ISSUE THREAD

**Issue by FrankyPants** [leighsmith/midisport-macos#39]
Hi there!
First of all, a giant thank you for all the amazing work you are doing. Your drivers have saved several printers and other devices over the years. : ) Now I have another issue with my old Oxygen 8 USB Midi Controller. I'd like to save it if I can and have followed your driver installation instructions. 
Unfortunately the keyboard is still not recognized. All the files are where they should be.
Am I missing something?
Any help would be greatly appreciated!!
Thank you!
F.

**Comment by fvogel** [comment]
Try to reconnect with different USB cables. 
On my end, with an Oxygen 8, some are working, other not.
Good luck.

**Comment by FrankyPants** [comment]
Well I'll be damned! Thank you Frédéric, this did the trick! I should have tested that right away, stupid me. Thank you! My oxygen 8 is saved :)

**Comment by fvogel** [comment]
Good to hear.
Now that you are connected, you could use Midi Monitor app to view how rotating buttons send info. Rotating button #1 had unexpected behaviour while all others were fine, for example.
Also, you might want to change the title of this thread and add "resolved" to it so that other github visitors do not get confused and think this software does not work on Big Sur. Thanks.
